#!/bin/sh
[ "$ACTION" = add ] || exit

NPROCS="$(grep -c "^processor.*:" /proc/cpuinfo)"
[ "$NPROCS" -gt 1 ] || exit

PROC_MASK="$(( (1 << $NPROCS) - 1 ))"

find_irq_cpu() {
	local dev="$1"
	local match="$(grep -m 1 "$dev\$" /proc/interrupts)"
	local cpu=0

	[ -n "$match" ] && {
		set -- $match
		shift
		for cur in $(seq 1 $NPROCS); do
			[ "$1" -gt 0 ] && {
				cpu=$(($cur - 1))
				break
			}
			shift
		done
	}

	echo "$cpu"
}

set_hex_val() {
	local file="$1"
	local val="$2"
	val="$(printf %x "$val")"
	[ -n "$DEBUG" ] && echo "$file = $val"
	echo "$val" > "$file"
}

packet_steering="1"
[ "$packet_steering" != 1 ] && exit 0

exec 512>/var/lock/smp_tune.lock
flock 512 || exit 1

for dev in /sys/class/net/*; do
	[ -d "$dev" ] || continue

	# ignore virtual interfaces
	[ -n "$(ls "${dev}/" | grep '^lower_')" ] && continue
	[ -d "${dev}/device" ] || continue

	device="$(readlink "${dev}/device")"
	device="$(basename "$device")"
	irq_cpu="$(find_irq_cpu "$device")"
	irq_cpu_mask="$((1 << $irq_cpu))"


	# ignore dsa slave ports for RPS
	subsys="$(readlink "${dev}/device/subsystem")"
	subsys="$(basename "$subsys")"
	[ "$subsys" = "mdio_bus" ] && continue
	taskset -a -p 8 $(pgrep mt76-tx)
	echo "3" > "/sys/class/net/eth0/queues/rx-0/rps_cpus"
	echo "3" > "/sys/class/net/wan/queues/rx-0/rps_cpus"
	echo "3" > "/sys/class/net/lan1/queues/rx-0/rps_cpus"
	echo "3" > "/sys/class/net/lan2/queues/rx-0/rps_cpus"
	echo "3" > "/sys/class/net/lan3/queues/rx-0/rps_cpus"
	echo "3" > "/sys/class/net/lan4/queues/rx-0/rps_cpus"
	echo "3" > "/sys/class/net/ra0/queues/rx-0/rps_cpus"
	echo "3" > "/sys/class/net/rax0/queues/rx-0/rps_cpus"
	echo "4" > "/proc/irq/23/smp_affinity"
	echo "4" > "/proc/irq/24/smp_affinity"
	echo "8" > "/proc/irq/21/smp_affinity"
done

